Fix: added || true to allow the log to be writen

diff --git a/.github/workflows/assignment4.yml b/.github/workflows/assignment4.yml
--- a/.github/workflows/assignment4.yml
+++ b/.github/workflows/assignment4.yml
@@ -27,7 +27,7 @@ jobs:
           echo "Yossi Peleg" >> log.txt  # You can change this if needed
 
           # Build images using docker-compose
-          docker-compose -f docker-compose.yml build
+          docker-compose -f docker-compose.yml build || true # To continue even if the build fails
           build_status=$?
           
           if [ $build_status -eq 0 ]; then
